### ISSUE TITLE
Please add a license to this repo

### ISSUE THREAD

**Issue by mbrukman** [flagello/redis-janusgraph-storage-backend#2]
Great project! Thanks for creating a JanusGraph backend using Redis.

Could you please add an explicit LICENSE file to the repo so that it's clear under what terms the content is provided, and under what terms user contributions are licensed?

Per [GitHub docs on licensing](https://help.github.com/articles/licensing-a-repository/#choosing-the-right-license):

> [...] without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license.

Thanks!

**Comment by flagello** [comment]
Hi @mbrukman, thanks for noticing! While it’s in the package’s files, I forgot to add it to the repo. Thanks! See https://github.com/flagello/redis-janusgraph-storage-backend/commit/fb1b1c2dfdab9e192bc7ade9e5bde2cf8549bba2.
